# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
paginate_path: "page:num"
#relative_permalinks: true

plugins: [jekyll-paginate]
# Setup
title:               Poole
tagline:             The Jekyll Butler
url:                 http://getpoole.com
paginate:            5
baseurl:             http://orduek.github.io/poole/

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Tobias Spiller & Or Duek 
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
